export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";

export const CHECK_USER_STATUS = "CHECK_USER_STATUS";

export const SIGNIN_CALLBACK = "SIGNIN_CALLBACK";