export const SEARCH_CATEGORY_REQUEST = "SEARCH_CATEGORY_REQUEST"
export const SEARCH_CATEGORY_SUCCESS = "SEARCH_CATEGORY_SUCCESS"
export const SEARCH_CATEGORY_FAILURE = "SEARCH_CATEGORY_FAILURE"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST"
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE"